PokemonMansion_B1F_Text_LewisIntro::
    .string "Uh-oh…\n"
    .string "Where am I now?$"

PokemonMansion_B1F_Text_LewisDefeat::
    .string "Awooh!$"

PokemonMansion_B1F_Text_LewisPostBattle::
    .string "You can find stuff lying around.\n"
    .string "The residents must've left them.$"

PokemonMansion_B1F_Text_IvanIntro::
    .string "This place is ideal for a lab.\n"
    .string "Look at all this space.$"

PokemonMansion_B1F_Text_IvanDefeat::
    .string "What was that for?$"

PokemonMansion_B1F_Text_IvanPostBattle::
    .string "I like it here.\n"
    .string "It's conducive to my studies.$"

PokemonMansion_B1F_Text_EugeneIntro::
    .string "…It worked too well. We couldn't\n"
    .string "control it, and YOU CAN'T\p"
    .string "control it! Nobody, NOBODY!\p"
    
PokemonMansion_B1F_Text_EugeneDefeat::
    .string "…$"

PokemonMansion_B1F_Text_EugenePostBattle::
    .string "…We thought it could be controlled.\p"
    .string "How naive of us to think we could\n"
    .string "become like ARCEUS.\p"
    .string "…But, you, YOU!! You can stop it;\n"
    .string "capture MEWTWO.$"

PokemonMansion_B1F_Text_EugeneEugenics::
    .string "With my knowledge on POKéMON\n"
    .string "GENETICS,\p"
    .string "I could perhaps, …but no.\p"
    .string "You've proven your strength and\n"
    .string "I can provide assistance.\p"
    .string "So, which POKéMON shall I inspect?$"

PokemonMansion_B1F_Text_EugeneEugenicsDeclined::
    .string "…Do you not want my assistance?$"

PokemonMansion_B1F_Text_EugeneEugenicsBadEgg::
    .string "Have you learned nothing from my tale?!$"

PokemonMansion_B1F_Text_IVEugenicsPrepNoIVs::
    .string "I shall begin at once.$"

PokemonMansion_B1F_Text_EugeneEugenicsComplete::
    .string "I … have finished.$"

PokemonMansion_B1F_Text_MewtwoIsFarTooPowerful::
    .string "Diary: Sept. 1\n"
    .string "MEWTWO is far too powerful.\p"
    .string "We have failed to curb its vicious\n"
    .string "tendencies…$"

